import Link from "next/link";
import { notFound } from "next/navigation";
import { addPayment, deleteInvoice, updateInvoiceStatus } from "@/app/actions";
import { Shell } from "@/components/shell";
import { PrintButton } from "@/components/print-button";
import { getWorkspace } from "@/lib/workspace";
import { FormButton } from "@/components/form-button";
const money=(v:number|string)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v));
export default async function InvoiceDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const {id}=await params; const q=await searchParams; const w=await getWorkspace();
 const {data:invoice}=await w.supabase.from("invoices").select("*,customers(name,email,phone,company_name)").eq("id",id).eq("company_id",w.companyId).maybeSingle(); if(!invoice)notFound();
 const [{data:items},{data:payments}]=await Promise.all([w.supabase.from("invoice_items").select("*").eq("invoice_id",id).order("created_at"),w.supabase.from("payments").select("*").eq("invoice_id",id).order("payment_date",{ascending:false})]);
 const paid=(payments??[]).reduce((s,p)=>s+Number(p.amount),0); const balance=Math.max(0,Number(invoice.total)-paid); const c=invoice.customers as {name:string;email:string|null;phone:string|null;company_name:string|null}|null; const today=new Date().toISOString().slice(0,10);
 return <Shell company={w.companyName}><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/invoices" className="text-sm font-bold text-blue-700">← Back to invoices</Link><h1 className="mt-2 text-3xl font-black">{invoice.invoice_number}</h1></div><PrintButton/></div>{q.error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{q.error}</p>}
 <section className="card mt-6 print:border-0 print:shadow-none"><div className="flex flex-wrap justify-between gap-8 border-b pb-6"><div><p className="text-2xl font-black">{w.companyName}</p><p className="mt-1 text-slate-500">Business invoice</p></div><div className="text-right"><p className="text-sm text-slate-500">Status</p><p className="font-black uppercase">{invoice.status}</p><p className="mt-2 text-sm">Issued {invoice.issue_date}<br/>Due {invoice.due_date}</p></div></div><div className="grid gap-6 border-b py-6 md:grid-cols-2"><div><p className="text-sm font-bold uppercase text-slate-500">Bill to</p><p className="mt-2 text-lg font-black">{c?.company_name||c?.name}</p><p className="text-sm text-slate-600">{c?.name}<br/>{c?.email}<br/>{c?.phone}</p></div><div className="md:text-right"><p className="text-sm font-bold uppercase text-slate-500">Balance due</p><p className="mt-2 text-3xl font-black">{money(balance)}</p></div></div>
 <div className="overflow-x-auto"><table className="mt-6 w-full min-w-[600px]"><thead><tr className="border-b text-left text-sm text-slate-500"><th className="py-3">Description</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Price</th><th className="py-3 text-right">Total</th></tr></thead><tbody>{items?.map(x=><tr key={x.id} className="border-b"><td className="py-4 font-bold">{x.description}</td><td className="py-4 text-right">{x.quantity}</td><td className="py-4 text-right">{money(x.unit_price)}</td><td className="py-4 text-right font-bold">{money(x.total)}</td></tr>)}</tbody></table></div>
 <div className="ml-auto mt-6 max-w-sm space-y-2"><div className="flex justify-between"><span>Subtotal</span><b>{money(invoice.subtotal)}</b></div><div className="flex justify-between"><span>Tax</span><b>{money(invoice.tax)}</b></div><div className="flex justify-between"><span>Discount</span><b>-{money(invoice.discount)}</b></div><div className="flex justify-between border-t pt-3 text-xl"><span>Total</span><b>{money(invoice.total)}</b></div><div className="flex justify-between text-emerald-700"><span>Paid</span><b>{money(paid)}</b></div></div>{invoice.notes&&<div className="mt-8 rounded-lg bg-slate-50 p-4"><p className="text-sm font-bold">Notes</p><p className="mt-1 text-sm text-slate-600">{invoice.notes}</p></div>}</section>
 <div className="mt-6 grid gap-6 lg:grid-cols-2 print:hidden"><form action={updateInvoiceStatus} className="card space-y-4"><h2 className="text-xl font-black">Update status</h2><input type="hidden" name="id" value={id}/><select name="status" defaultValue={invoice.status}><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select><FormButton className="btn w-full" pendingText="Updating...">Save status</FormButton></form><form action={addPayment} className="card space-y-4"><h2 className="text-xl font-black">Record payment</h2><input type="hidden" name="invoice_id" value={id}/><div className="grid grid-cols-2 gap-3"><label><span className="label">Amount</span><input name="amount" type="number" min="0.01" step="0.01" defaultValue={balance.toFixed(2)} required/></label><label><span className="label">Date</span><input name="payment_date" type="date" defaultValue={today} required/></label></div><label><span className="label">Method</span><select name="payment_method"><option>Cash</option><option>Bank Transfer</option><option>GCash</option><option>PayPal</option><option>Credit Card</option></select></label><label><span className="label">Reference</span><input name="reference"/></label><FormButton className="btn w-full" disabled={balance<=0} pendingText="Recording payment...">Add payment</FormButton></form></div>
 <section className="card mt-6 print:hidden"><h2 className="text-xl font-black">Payment history</h2><div className="mt-4 space-y-3">{payments?.length?payments.map(p=><div key={p.id} className="flex justify-between border-b pb-3"><div><b>{p.payment_method}</b><p className="text-sm text-slate-500">{p.payment_date}{p.reference?` • ${p.reference}`:""}</p></div><b>{money(p.amount)}</b></div>):<p className="text-slate-500">No payments recorded.</p>}</div></section>
 <form action={deleteInvoice} className="mt-6 print:hidden"><input type="hidden" name="id" value={id}/><button className="text-sm font-bold text-red-600">Delete invoice</button></form></div></Shell>
}